name: PlantUML Generator

on:
  push:
    paths:
      - 'Readme.md'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate PlantUML
      uses: Timmy/plantuml-action@v1
      with:
        args: '-tvsvg Readme.md'
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.svg || true
        git commit -m "Update diagrams" || true
        git push
